export const QUERY_KEY = {
  SEARCH_VIDEO: 'SEARCH_VIDEO',
  GET_VIDEO_INFO: 'GET_VIDEO_INFO',
  GET_COMMENT_INFO: 'GET_COMMENT_INFO',
  CHANNEL_INFO: 'CHANNEL_INFO',
  GET_POPULAR_VIDEO_LIST: 'GET_POPULAR_VIDEO_LIST',
};
